//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookPlace
    {
        public int BookPlaceID { get; set; }
        public Nullable<int> FKBookID { get; set; }
        public Nullable<int> FKPlaceID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string ExtraLocationInfo { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Place Place { get; set; }
    }
}
