//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedBook
    {
        public int IssuedBookID { get; set; }
        public Nullable<int> FKBookID { get; set; }
        public Nullable<int> FKStudentID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string isActive { get; set; }
        public string Status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
